version: '3.0'

services:
    app:
        image: 'andrewc2020/apcm:latest'
        build: '.'
        deploy:
           replicas: 1
           restart_policy:
              condition: on-failure
        ports:
            - 3000:80
        networks:
            - webnet
        

    productservice:
        image: 'andrewc2020/productservice'
        build: '~/productservice'
        
        ports: 
            - 4000:4000
networks:
     webnet:
          